In [2]:
#NAME :HEMA ARULARASI .M
#REGISTER NO:21UAI035

In [3]:
#11.
def pypart(n):
    myList = []
    for i in range(1,n+1):
        myList.append("*"*i)
    print("\n".join(myList))
n = 7
pypart(n)

*
**
***
****
*****
******
*******


In [4]:
#12.
def remove_chars(word, n):
    print('Original string:', word)
    x = word[n:]
    return x

print("Removing characters from a string")
print(remove_chars("Hema Arularasi", 4))
print(remove_chars("Hema Arularasi", 2))

Removing characters from a string
Original string: Hema Arularasi
 Arularasi
Original string: Hema Arularasi
ma Arularasi


In [ ]:
#13.
for i in range(5): 
    n = int(input("Enter a number: ")) 
 
    if n % 5 == 0: 
        print(n) 

In [6]:
#14.
words = ["hi", "hi", "hi","Hi","hi", "welcome"]
n_hi = words.count("hi")
print(n_hi)

4


In [7]:
#15.
num = 11
for n in range(1, num):
    for i in range(1, n+1):
        print(i, end=" ")
    print("")

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 10 


In [11]:
#16.
number = int(input("Please Enter any Value: "))
reverse = 0
temp = number
while(temp > 0):
    Reminder = temp % 10
    reverse = (reverse * 10) + Reminder
    temp = temp //10
    print("Reverse of it is = %d" %reverse)
if(number == reverse):
    print("%d is a Palindrome" %number)
else:
    print("%d is Not" %number)

Please Enter any Value: 173
Reverse of it is = 3
Reverse of it is = 37
Reverse of it is = 371
173 is Not


In [13]:
#17.string
myList = [13,28,73,25,89,60]
print("Initial List : ", myList)
length = len(myList)
temp = myList[0]
myList[0] = myList[length - 1]
myList[length - 1] = temp

print("List after Swapping : ", myList)

Initial List :  [13, 28, 73, 25, 89, 60]
List after Swapping :  [60, 28, 73, 25, 89, 13]


In [14]:
#18.
def swapPositions(list, pos1, pos2):
     
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
 
List = [83, 57, 61, 100]
pos1, pos2  = 1, 3
 
print(swapPositions(List, pos1-1, pos2-1))

[61, 57, 83, 100]


In [15]:
#19.
test_list = [ 58,4,23,96,17 ]
print ("The list is : " + str(test_list))
counter = 0
for i in test_list:
    counter = counter + 1
print ("Length of list using naive method is : " + str(counter))

The list is : [58, 4, 23, 96, 17]
Length of list using naive method is : 5


In [17]:
#20.
def maximum(a, b):
      
    if a >= b:
        return a
    else:
        return b
a = 18
b = 91
print(maximum(a, b))

91


In [18]:
#21.
def minimum(a, b):
      
    if a <= b:
        return a
    else:
        return b
a = 63
b = 79
print(minimum(a, b))

63


In [21]:
#22.
string = 'malayalam'
half = int(len(string) / 2)
 
if len(string) % 2 == 0:  # even
    first_str = string[:half]
    second_str = string[half:]
else:  # odd
    first_str = string[:half]
    second_str = string[half+1:]
if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')
if first_str == second_str[::-1]: 
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')


malayalam string is not symmertical
malayalam string is palindrome


In [22]:
#23.
string = "Hello Everyone, This is Hema"
s = string.split()[::-1]
l = []
for i in s:
   
    l.append(i)

print(" ".join(l))

Hema is This Everyone, Hello


In [23]:
#24.
test_str = "Hemarthi" 
print ("The original string is : " + test_str)
new_str = ""
  
for i in range(len(test_str)):
    if i != 2:
        new_str = new_str + test_str[i] 
print ("The string after removal of i'th character : " + new_str)

The original string is : Hemarthi
The string after removal of i'th character : Hearthi


In [24]:
#25.tuples
import sys
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Hema", "Arthi", "Vijay", "Usha", "Murugan")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
print("Size of Tuple1: " + str(sys.getsizeof(Tuple1)) + "bytes")
print("Size of Tuple2: " + str(sys.getsizeof(Tuple2)) + "bytes")
print("Size of Tuple3: " + str(sys.getsizeof(Tuple3)) + "bytes")

Size of Tuple1: 88bytes
Size of Tuple2: 80bytes
Size of Tuple3: 72bytes


In [25]:
#26.
test_tup = (6, 30, 2, 9, 10, 5)
print("The original tuple is : " + str(test_tup))
K = 2
res = []
test_tup = list(sorted(test_tup))
 
for idx, val in enumerate(test_tup):
    if idx < K or idx >= len(test_tup) - K:
        res.append(val)
res = tuple(res)
print("The extracted values : " + str(res))

The original tuple is : (6, 30, 2, 9, 10, 5)
The extracted values : (2, 5, 10, 30)


In [26]:
#27.
test_tup = (81,36,72,77,52)
print("The original tuple is : " + str(test_tup)) 
res = sum(list(test_tup))
print("The summation of tuple elements are : " + str(res)) 

The original tuple is : (81, 36, 72, 77, 52)
The summation of tuple elements are : 318


In [27]:
#28.DICTIONARY
def dictionairy():
    key_value = {}
    key_value[2] = 21
    key_value[1] = 16
    key_value[5] = 5
    key_value[4] = 94
    key_value[6] = 72
    key_value[3] = 2004
 
    print("Task 1:-\n")
 
    print("key_value", key_value)

    for i in sorted(key_value.keys()):
        print(i, end=" ")
 
 
def main():
    
    dictionairy()
if __name__ == "__main__":
    main()

Task 1:-

key_value {2: 21, 1: 16, 5: 5, 4: 94, 6: 72, 3: 2004}
1 2 3 4 5 6 

In [28]:
#33
import random as rn
dict = {}
x, y, z = 46,25,16
dict[x, y, z] = x + y - z;
x, y, z = 6, 8, 1
dict[x, y, z] = x + y - z;
print(dict)

{(46, 25, 16): 55, (6, 8, 1): 13}


In [29]:
#34
def returnSum(myDict):
 
    list = []
    for i in myDict:
        list.append(myDict[i])
    final = sum(list)
 
    return final
dict = {'a': 783, 'b': 159, 'c': 900}
print("Sum :", returnSum(dict))

Sum : 1842


In [30]:
#35 SET
import sys
Set1 = {"a", 1, "h", 2, "l", 3}
Set2 = {"Kamali", "Viji", "Saman", "Shofia", "Lucky", "Sreejaa"}
Set3 = {(1, "Rat"), ( 2, "Lion"), (3, "Tiger")}

print("Size of Set1: " + str(sys.getsizeof(Set1)) + "bytes")
print("Size of Set2: " + str(sys.getsizeof(Set2)) + "bytes")
print("Size of Set3: " + str(sys.getsizeof(Set3)) + "bytes")

Size of Set1: 472bytes
Size of Set2: 472bytes
Size of Set3: 216bytes


In [31]:
#36
test_set = set("HEma ArulArasi")

for val in test_set:
    print(val)

i
l
a
 
r
s
A
E
u
H
m


In [32]:
#37
gfg_list=[19,13,87,16,43]
min_ele,max_ele=gfg_list[0],gfg_list[0] 
for i in range(1,len(gfg_list)):
    if gfg_list[i]<min_ele:
        min_ele=gfg_list[i]
    if gfg_list[i]>max_ele:
        max_ele=gfg_list[i]
print('Minimum Element in the list',gfg_list,'is',min_ele)
print('Maximum Element in the list',gfg_list,'is',max_ele)

Minimum Element in the list [19, 13, 87, 16, 43] is 13
Maximum Element in the list [19, 13, 87, 16, 43] is 87


In [33]:
#38 MATRIX
test_list = [[12,52,64], [2,4,0], [8,5,2], [75,48,96]]
print("The original list : " + str(test_list))
res = {test_list[0][ele] :  test_list[ele + 1] for ele in range(len(test_list) - 1)}
print("The Assigned Matrix : " + str(res))

The original list : [[12, 52, 64], [2, 4, 0], [8, 5, 2], [75, 48, 96]]
The Assigned Matrix : {12: [2, 4, 0], 52: [8, 5, 2], 64: [75, 48, 96]}


In [34]:
#39 
import numpy as np
A = np.array([[41, 52], [37, 6]])
  
B = np.array([[19, 85], [96, 45]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[41 52]
 [37  6]]
Printing elements of second matrix
[[19 85]
 [96 45]]
Addition of two matrix
[[ 60 137]
 [133  51]]


In [35]:
#40
from itertools import groupby
test_list = [46,16,32,84,26]
print("The original list : " + str(test_list))
res = [list(val) for key, val in groupby(sorted(test_list))]  
print("Matrix after grouping : " + str(res))

The original list : [46, 16, 32, 84, 26]
Matrix after grouping : [[16], [26], [32], [46], [84]]


In [62]:
#41FUNCTIONS 
import inspect
import collections
print(inspect.signature(collections.Counter))

(iterable=None, /, **kwds)


In [36]:
#42
def GFG(name, num):
    print("Hello from ", name + ', ' + num)
  
  
GFG("Hema Arularasi", "18")

Hello from  Hema Arularasi, 18


In [37]:
#43
def power(N, P):
 
    if P == 0:  
        return 1
   
    return (N*power(N, P-1)) 
N = 2
P = 3
 
print(power(N, P))

8
